---
pool: 
  name: default
  vmImage: 'ubuntu-latest'

trigger:
  - main

steps:
  - script: sudo apt install maven
  - task: maven@3
    inputs:
      mavenPOMFile: 'pom.xml'
      goals: 'package'
      javaHomeOption: 'Path'
      jdkVersionOption: '1.17' 
      jdkDirectory: /usr/lib/jvm/java-17-openjdk-amd64/bin/java

