---
pool: 
  name: default
  vmImage: 'ubuntu-latest'

trigger:
  - main

steps:
  - task: maven@3
    inputs:
      mavenPOMFile: 'pom.xml'
      goals: 'package'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'Path'
      jdkVersionOption: '1.17' 
      jdkDirectory: /usr/lib/jvm/java-17-openjdk-amd64/bin/java
      mavenVersionOption: 'Path'
      mavenDirectory: /tmp/apache-maven-3.9.0
