---
pool:
  name: 'Azure Pipeline'
  vmImage: 'ubuntu-latest'

trigger:
  - main

steps:
  - task: maven@3
    inputs:
      mavenPOMFile: 'pom.xml'
      jdkVersionOption: '1.17'
      goals: 'package'