---
pool: 
  name: default

trigger:
  - main

parameters:
  - name: goals
    type: string
    displayName: maven goals
    default: 'package'
    values:
      - 'package'
      - 'clean'
      - 'install'
      - 'compile'
  - name: mavenPOMFile
    displayName: mavenpomfile
    type: string
    default: 'pom.xml'


steps:
  - task: maven@3
    inputs:
      mavenPOMFile: "${{ parameters.mavenpomfile }}"
      goals: "${{ parameters.goals }}"
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'Path'
      jdkVersionOption: '1.17'
      jdkDirectory: /usr/lib/jvm/java-17-openjdk-amd64
      mavenVersionOption: 'Path'
      mavenDirectory: /opt/maven
