---
pool:
  name: default
  vmImage: 'ubuntu-latest'

trigger:
  - main

steps:
  - script: sudo apt install openjdk-17-jdk
    displayName: 'install java'
  
  - script: sudo apt install maven
    displayName: 'install maven'

  